---
- name: Check if YARN repo is already configured.
  stat: path={{ yarn_rhel_repofile_path }}
  register: yarn_repofile_result

- name: Install YARN YUM repo.
  get_url:
    url: "{{ yarn_rhel_repo_url }}"
    dest: "{{ yarn_rhel_repofile_path }}"
    mode: 0644
  register: result
  until: '"failed" not in result'
  retries: 3
  delay: 5
  when: not yarn_repofile_result.stat.exists

- name: Import YARN GPG key.
  rpm_key:
    key: "{{ yarn_rhel_repo_gpg_key_url }}"
    state: present
  when: not yarn_repofile_result.stat.exists

- name: Install http-parser | Centos/Rhel 7
  yum:
    name: https://kojipkgs.fedoraproject.org//packages/http-parser/2.7.1/3.el7/x86_64/http-parser-2.7.1-3.el7.x86_64.rpm
    state: present
  when: ansible_distribution_major_version == '7'
  register: http_parser_result
  failed_when: http_parser_result.rc != 0 and ("Nothing to do" not in http_parser_result.stderr)

- name: Install NodeJS package for yarn dependency
  package: name=nodejs state=latest
